"""Model comparison report on VALIDATION: markdown table + precision-recall curves.

Uses the latest run of each (model, split) in reports/metrics/experiments.csv and reloads
that run's logged model from MLflow to draw its PR curve (no retraining). The reloaded
model's PR-AUC is checked against the logged value.

    python -m fraud_detection.compare
"""

from __future__ import annotations

import logging
import math
from pathlib import Path

import matplotlib

matplotlib.use("Agg")  # file output only, no window

import matplotlib.pyplot as plt  # noqa: E402
import mlflow.sklearn  # noqa: E402
import pandas as pd  # noqa: E402
from sklearn.metrics import average_precision_score, precision_recall_curve  # noqa: E402

from fraud_detection.config import Config, load_config  # noqa: E402
from fraud_detection.features import MODEL_FEATURES  # noqa: E402
from fraud_detection.schema import TARGET  # noqa: E402
from fraud_detection.train import SPLIT_NAMES, load_part, setup_mlflow  # noqa: E402

logger = logging.getLogger(__name__)

TABLE_COLUMNS = {
    "model": "model",
    "split": "split",
    "pr_auc": "pr_auc",
    "roc_auc": "roc_auc",
    "recall": "recall@0.5",
    "precision": "precision@0.5",
    "fit_seconds": "fit_seconds",
}


def latest_runs(experiments_csv: Path) -> pd.DataFrame:
    """Most recent row per (model, split); older re-runs are ignored."""
    df = pd.read_csv(experiments_csv)
    df = df.sort_values("timestamp").groupby(["model", "split"], as_index=False).tail(1)
    return df.reset_index(drop=True)


def to_markdown_table(df: pd.DataFrame) -> str:
    """Render a DataFrame as a GitHub markdown table (floats to 4 decimals)."""

    def fmt(value: object) -> str:
        return f"{value:.4f}" if isinstance(value, float) else str(value)

    header = "| " + " | ".join(df.columns) + " |"
    divider = "|" + "|".join("---" for _ in df.columns) + "|"
    rows = ["| " + " | ".join(fmt(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([header, divider, *rows])


def comparison_markdown(runs: pd.DataFrame, valid_fraud: dict[str, int]) -> str:
    """One table per split, sorted by validation PR-AUC (best first)."""
    lines = [
        "# Model comparison — validation set",
        "",
        "Generated by `python -m fraud_detection.compare` from `reports/metrics/experiments.csv`",
        "(latest run per model and split). All numbers are on the VALIDATION part; the test",
        "set has not been used. Ranking metric: PR-AUC. Recall/precision are at a fixed 0.5",
        "threshold and are not a fair cross-model comparison (thresholds are tuned in Phase 8).",
        "",
    ]
    for split in SPLIT_NAMES:
        part = runs[runs["split"] == split].sort_values("pr_auc", ascending=False)
        if part.empty:
            continue
        table = part[list(TABLE_COLUMNS)].rename(columns=TABLE_COLUMNS)
        lines += [
            f"## {split} split (validation fraud cases: {valid_fraud[split]})",
            "",
            to_markdown_table(table),
            "",
        ]
    return "\n".join(lines)


def plot_pr_curves(runs: pd.DataFrame, split: str, config: Config, out_path: Path) -> None:
    """Draw every model's validation PR curve for one split, reloading models from MLflow."""
    valid = load_part(split, "valid", config.paths.processed_dir)
    X, y = valid[MODEL_FEATURES], valid[TARGET]

    fig, ax = plt.subplots(figsize=(8, 6))
    part = runs[runs["split"] == split].sort_values("pr_auc", ascending=False)
    for row in part.itertuples():
        model = mlflow.sklearn.load_model(f"runs:/{row.run_id}/model")
        proba = model.predict_proba(X)[:, 1]
        ap = average_precision_score(y, proba)
        if not math.isclose(ap, row.pr_auc, rel_tol=1e-9, abs_tol=1e-12):
            raise RuntimeError(
                f"{row.model}/{split}: reloaded PR-AUC {ap:.6f} != logged {row.pr_auc:.6f}"
            )
        precision, recall, _ = precision_recall_curve(y, proba)
        ax.step(recall, precision, where="post", label=f"{row.model} (AP={ap:.3f})")

    ax.set_xlabel("Recall")
    ax.set_ylabel("Precision")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1.02)
    ax.set_title(f"Precision-recall curves — {split} split, validation (n fraud = {int(y.sum())})")
    ax.legend(loc="lower left", fontsize=8)
    ax.grid(alpha=0.3)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    logger.info("Saved %s", out_path)


def main() -> None:
    """CLI: write model_comparison.md and pr_curves_{split}.png."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    config = load_config()
    setup_mlflow(config)
    runs = latest_runs(config.paths.metrics_dir / "experiments.csv")

    valid_fraud = {
        s: int(load_part(s, "valid", config.paths.processed_dir)[TARGET].sum()) for s in SPLIT_NAMES
    }
    md = comparison_markdown(runs, valid_fraud)
    md_path = config.paths.metrics_dir / "model_comparison.md"
    md_path.write_text(md + "\n", encoding="utf-8")
    logger.info("Saved %s", md_path)

    for split in SPLIT_NAMES:
        plot_pr_curves(runs, split, config, config.paths.figures_dir / f"pr_curves_{split}.png")
    print(md)


if __name__ == "__main__":
    main()
