"""Generate requirements-api.lock: exact pins for the API's runtime dependency closure.

Starts from requirements-api.txt, follows every package's declared requirements (including
extras such as uvicorn[standard]) and pins the version installed in this environment, which
is the training environment (requirements-lock.txt), so serving == training versions
(docs/rules.md rule 21). Markers are evaluated for both Windows (dev) and Linux (Docker):
- needed on both -> plain pin;
- needed on one platform only -> pin + environment marker;
- needed on Linux only but not installable here (e.g. uvloop) -> written as a comment, so it
  is visible but never pinned to a version that was not tested.
The script fails if any pin disagrees with requirements-lock.txt.

One explicit runtime substitution (KING-approved, Phase 13), see RUNTIME_SUBSTITUTES:
xgboost-cpu 3.2.0 (API image) <-> xgboost 3.2.0 (training env / model_meta.json). It is the same
version and ships the same `xgboost` module; only the CUDA/NCCL GPU parts (~700 MB on Linux) are
absent. Its version is checked against the training lock's xgboost pin, as strictly as any other.

    python scripts/make_api_lock.py
"""

from __future__ import annotations

import importlib.metadata as md
import re
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parents[1]
WINDOWS = {**default_environment(), "sys_platform": "win32", "platform_system": "Windows",
           "os_name": "nt"}  # fmt: skip
LINUX = {**default_environment(), "sys_platform": "linux", "platform_system": "Linux",
         "os_name": "posix"}  # fmt: skip


# API package -> the training package it stands in for. Verified from the xgboost-cpu 3.2.0
# wheel METADATA: Requires-Dist equals xgboost 3.2.0's minus the single GPU line
# `nvidia-nccl-cu12; platform_system == 'Linux'` (dropped below). Add entries only with approval.
RUNTIME_SUBSTITUTES: dict[str, dict] = {
    "xgboost-cpu": {"training_package": "xgboost", "drop_requirements": {"nvidia-nccl-cu12"}},
}


def _installed(name: str) -> tuple[str | None, list[str]]:
    """(version, requirements) from the training env, honouring RUNTIME_SUBSTITUTES."""
    sub = RUNTIME_SUBSTITUTES.get(canonicalize_name(name))
    source = sub["training_package"] if sub else name
    try:
        version = md.version(source)
    except md.PackageNotFoundError:
        return None, []
    requires = md.requires(source) or []
    if sub:
        drop = sub["drop_requirements"]
        requires = [r for r in requires if canonicalize_name(Requirement(r).name) not in drop]
    return version, requires


def training_name(name: str) -> str:
    """Name to look up in requirements-lock.txt (the substituted training package, if any)."""
    sub = RUNTIME_SUBSTITUTES.get(canonicalize_name(name))
    return canonicalize_name(sub["training_package"]) if sub else canonicalize_name(name)


def _applies(req: Requirement, env: dict[str, str], extras: set[str]) -> bool:
    if req.marker is None:
        return True
    return any(req.marker.evaluate({**env, "extra": e}) for e in (extras or {""}))


def closure(roots: list[Requirement]) -> dict[str, dict]:
    """name -> {"version", "platforms"} for everything reachable from roots."""
    found: dict[str, dict] = {}
    queue = [(r, {"win", "linux"}) for r in roots]
    while queue:
        req, platforms = queue.pop()
        name = canonicalize_name(req.name)
        version, requires = _installed(req.name)
        entry = found.setdefault(name, {"version": version, "platforms": set(), "extras": set(),
                                        "display": req.name})  # fmt: skip
        new_platforms = platforms - entry["platforms"]
        new_extras = set(req.extras) - entry["extras"]
        if not new_platforms and not new_extras:
            continue
        entry["platforms"] |= platforms
        entry["extras"] |= set(req.extras)
        if version is None:
            continue
        for raw in requires:
            child = Requirement(raw)
            child_platforms = {
                p for p, env in (("win", WINDOWS), ("linux", LINUX))
                if p in entry["platforms"] and _applies(child, env, entry["extras"])
            }  # fmt: skip
            if child_platforms:
                queue.append((child, child_platforms))
    return found


def main() -> None:
    roots = []
    for line in (ROOT / "requirements-api.txt").read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            roots.append(Requirement(line))
    training = {}
    for line in (ROOT / "requirements-lock.txt").read_text(encoding="utf-8").splitlines():
        if m := re.match(r"^([A-Za-z0-9_.\-]+)==(\S+)", line.strip()):
            training[canonicalize_name(m.group(1))] = m.group(2)

    lines = [
        "# requirements-api.lock — GENERATED by scripts/make_api_lock.py; do not edit by hand.",
        "# Exact pins for the API runtime (closure of requirements-api.txt), identical to the",
        "# training environment in requirements-lock.txt (docs/rules.md rule 21).",
    ]
    unpinned = []
    for name, e in sorted(closure(roots).items()):
        if e["version"] is None:
            where = "/".join(sorted(e["platforms"]))
            unpinned.append(f"# {e['display']}: required on {where} only; not installed in "
                            "the Windows build env, so NOT pinned")  # fmt: skip
            continue
        expected = training.get(training_name(name))  # same strict check for every package
        if expected != e["version"]:
            raise SystemExit(f"{name}=={e['version']} differs from requirements-lock.txt "
                             f"({training_name(name)}=={expected})")  # fmt: skip
        marker = ""
        if e["platforms"] == {"win"}:
            marker = ' ; sys_platform == "win32"'
        elif e["platforms"] == {"linux"}:
            marker = ' ; sys_platform != "win32"'
        lines.append(f"{e['display']}=={e['version']}{marker}")
    (ROOT / "requirements-api.lock").write_text("\n".join(lines + unpinned) + "\n",
                                                encoding="utf-8")  # fmt: skip
    print("\n".join(lines[3:] + unpinned))


if __name__ == "__main__":
    main()
